# Generated by Django 6.1 on 2026-08-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_contratacion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='salario',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='telefono',
        ),
    ]
